# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sun-Ming
brief-intro: BigData/JavaWeb Advanced Dev Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sun-ming.github.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:year/:month/:day/:title/

# other links
twitter_username: sun-ming
facebook_username: sun-ming
github_username: sun-ming
email: 416219573@qq.com
weibo_username: sun-ming
zhihu_username: sun-ming
linkedIn_username: sun-ming
dribbble_username: sun-ming

description_footer: 本站记录我软件开发的旅途风景！

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #sun-ming
disqus_shortname: #sun-ming

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: #cf8506e0ef223e57ff6239944e5d46a4
google_analytics_id: #UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
